import sys
sys.path.append("/ws-py/pp-protos")

import arrow

from random import randint
from tweet_types_pb2 import TweetRequest
from user_types_pb2 import LoginRequest
from user_types_pb2 import SignUpRequest



BAD_QUOTE = "We ask ourselves: Who am I to be brilliant, gorgeous, talented, fabulous? Actually, who are you not to be? You are a child of God. Your playing small does not serve the world. There is nothing enlightened about shrinking so that other people won't feel insecure around you. We are all meant to shine, as children do."
names = ['Olivia', 'Jacob', 'Emma', 'Ethan', 'Sophia', 'Noah', 'Isabella', 'Michael', 'Mia', 'Matthew', 'Ava', 'Mason', 'Emily', 'Joseph', 'Charlotte', 'Lucas', 'Madison', 'Daniel', 'Abigail', 'Alexander', 'Leah', 'Aiden', 'Amelia', 'Dylan', 'Sofia', 'James', 'Chloe', 'David', 'Grace', 'Jayden', 'Sarah', 'Benjamin', 'Ella', 'Ryan', 'Elizabeth', 'Logan', 'Avery', 'Anthony', 'Victoria', 'William', 'Gabriella', 'Christopher', 'Zoe', 'Jack', 'Harper', 'Nicholas', 'Scarlett', 'Samuel', 'Evelyn', 'Gabriel', 'Lily', 'Sebastian', 'Samantha', 'John', 'Hannah', 'Joshua', 'Riley', 'Jackson', 'Ariana', 'Andrew', 'Savannah', 'Oliver', 'Esther', 'Henry', 'Alexa', 'Elijah', 'Hailey', 'Carter', 'Natalie', 'Isaac', 'Maya', 'Nathan', 'Skylar', 'Owen', 'Arianna', 'Thomas', 'Layla', 'Aaron', 'Rachel', 'Christian', 'Gianna', 'Jonathan', 'Aria', 'Hunter', 'Ashley', 'Luke', 'Brianna', 'Adam', 'Penelope', 'Caleb', 'Anna', 'Julian', 'Zoey', 'Tyler', 'Aubrey', 'Chase', 'Camila', 'Evan', 'Valentina', 'Leo', 'Julia', 'Charles', 'Stella', 'Connor', 'Violet', 'Cameron', 'Allison', 'Adrian', 'Kayla', 'Jason', 'Alexandra', 'Eli', 'Sara', 'Justin', 'Claire', 'Zachary', 'Nora', 'Jeremiah', 'Eva', 'Josiah', 'Mila', 'Nathaniel', 'Kaylee', 'Kevin', 'Mackenzie', 'Robert', 'Kylie', 'Angel', 'Lillian', 'Brandon', 'Addison', 'Jordan', 'Madeline', 'Moshe', 'Aaliyah', 'Theodore', 'Bella', 'Austin', 'Genesis', 'Dominic', 'Chaya', 'Gavin', 'Miriam', 'Luca', 'Eliana', 'Vincent', 'Katherine', 'Isaiah', 'Madelyn', 'Brayden', 'Alice', 'Wyatt', 'Sophie', 'Ian', 'Angelina', 'Landon', 'Peyton', 'Grayson', 'Isabelle', 'Levi', 'Autumn', 'Ayden', 'Eleanor', 'Abraham', 'Maria', 'Kayden', 'Naomi', 'Max', 'Aurora', 'Jace', 'Adriana', 'Jaxon', 'Rivka', 'Jeremy', 'Lucy', 'Giovanni', 'Caroline', 'Parker', 'Alyssa', 'Xavier', 'Taylor', 'Hudson', 'Audrey', 'Steven', 'Quinn', 'Declan', 'Sadie', 'Kyle', 'Melanie', 'Jake', 'Chana', 'Jaxson', 'Julianna', 'Maxwell', 'Kimberly', 'George', 'Ellie', 'Blake', 'Emilia', 'Mateo', 'Juliana']
quotes = [
  "There will come a time when you believe everything is finished. That will be the beginning.",
  "Always bear in mind that your own resolution to succeed is more important than any other one thing.",
  "Luck is a dividend of sweat. The more you sweat, the luckier you get.",
  "The last 10 percent it takes to launch something takes as much energy as the first 90 percent.",
  "Don't worry about failures, worry about the chances you miss when you don't even try.",
  "I knew that if I failed I wouldn't regret that, but I knew the one thing I might regret is not trying.",
  "Both my mother and I were determined that we weren't going to stay on welfare. We always worked toward ... having a better life. We never had any doubts that we would.",
  "It is not the strongest of the species that survive, nor the most intelligent, but the one most responsive to change.",
  "There is only one boss: the customer. And he can fire everybody in the company, from the chairman on down, simply by spending his money somewhere else.",
  "It takes as much energy to wish as it does to plan.",
  "There is no security on the Earth, there is only opportunity.",
  "Being an optimist after you've got the very thing you want doesn't count.",
  "There are two kinds of failures: those who thought and never did, and those who did and never thought.",
  "Once you replace negative thoughts with positive ones, you'll start having positive results.",
  "Nothing works better than just improving your product.",
  "The greatest crime in the world is not developing your potential. When you do what you do best, you are helping not only yourself but the world.",
  "We are what we repeatedly do. Excellence, then, is not an act but a habit.",
  "The time to repair the roof is when the sun is shining.",
  "Conditions are never perfect. 'Someday' is a disease that will take your dreams to the grave with you.... If it's important to you and you want to do it 'eventually,' just do it and correct course along the way.",
  "Embrace what you don't know, especially in the beginning, because what you don't know can become your greatest asset. It ensures that you will absolutely be doing things different from everybody else.",
  "Even if I knew that tomorrow the world would go to pieces, I would still plant my apple tree.",
  "We must never be afraid to go too far, for success lies just beyond.",
  "It's not your job to like me, it's mine.",
  "Education is the key to unlock the golden door of freedom.",
  "Build your own dreams, or someone else will hire you to build theirs.",
  "There are two things people want more than sex and money: recognition and praise.",
  "If you want to lift yourself up, lift up someone else.",
  "Ambition is the path to success. Persistence is the vehicle you arrive in.",
  "Luck can only get you so far.",
  "Don't worry about failures, worry about the chances you miss when you don't even try.",
  "I always want to say to people who want to be rich and famous: 'Try being rich first.' See if that doesn't cover most of it.",
  "A good traveler has no fixed plans, and is not intent on arriving.",
  "I watched a small man with thick calluses on both hands work 15 and 16 hours a day ... who taught me all I needed to know about faith and hard work by the simple eloquence of his example.",
  "Aging is not 'lost youth' but a new stage of opportunity and strength.",
  "The limits of the possible can only be defined by going beyond them into the impossible.",
  "Be brave enough to live life creatively. The creative place where no one else has ever been.",
  "For me, the most fun is change or growth. There are definitely elements of both that I like. Launching a business is kind of like a motorboat: You can go very quickly and turn fast.",
  "We learn wisdom from failure much more than from success; we often discover what will do, by finding out what will not do; and probably he who never made a mistake never made a discovery.",
  "You can be the ripest, juciest peach in the world, and there are still going to be some people who hate peaches.",
  "I attribute my success to this: I never gave or took any excuse.",
  "Do not indulge in dreams of having what you have not, but reckon up the chief of the blessings you do possess, and then thankfully remember how you would crave for them if they were not yours.",
  "Always forgive your enemies. Nothing annoys them more.",
  "Build something 100 people love, not something one million people kind of like.",
  "Tough times never last, but tough people do.",
  "I don't know what your destiny will be, but one thing I know: The only ones among you who will be truly happy are those who have sought and found how to serve.",
  "Take chances, make mistakes. That's how you grow. Pain nourishes your courage. You have to fail in order to practice being brave.",
  "The hardest thing to do is to be true to yourself, especially when everybody is watching.",
  "Time is the coin of your life. It is the only coin you have, and only you can determine how it will be spent. Be careful lest you let other people spend it for you.",
  "Don't judge each day by the harvest you reap but by the seeds that you plant.",
  "Running a startup is like eating glass. You just start to like the taste of your own blood.",
  "There are two educations. One should teach us how to make a living and the other how to live.",
  "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
  "Try to be a rainbow in someone's cloud.",
  "The greater part of our misery or unhappiness is determined not by our circumstance but by our disposition.",
  "Early to bed and early to rise probably indicates unskilled labor.",
  "Always make a total effort, even when the odds are against you.",
  "Every moment and every event of every man's life on earth plants something in his soul.",
  "Leadership is the art of getting someone else to do something you want done because he wants to do it.",
  "Everything you've ever wanted is on the other side of fear.",
  "Always look for the fool in the deal. If you don't find one, it's you.",
  "I have not failed. I've just found 10,000 ways that won't work.",
  "The road to Easy Street goes through the sewer.",
  "I think the girl who is able to earn her own living and pay her own way should be as happy as anybody on Earth. The sense of independence and security is very sweet.",
  "Success is walking from failure to failure with no loss of enthusiasm.",
  "If you want to go fast, go alone. If you want to go far, go together.",
  "Life is a gift, and it offers us the privilege, opportunity, and responsibility to give something back by becoming more.",
  "One day, in retrospect, the years of struggle will strike you as the most beautiful.",
  "Know the true value of time; snatch, seize, and enjoy every moment of it.",
  "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light.",
  "Never use a machine gun to kill a rabbit.",
  "The most courageous act is still to think for yourself. Aloud.",
  "Life's like a movie; write your own ending, keep believing, keep pretending.",
  "Never doubt that a small group of thoughtful committed citizens can change the world. Indeed, it is the only thing that ever has.",
  "We convince by our presence.",
  "The successful warrior is the average man, with laser-like focus.",
  "A man who gives you less than what he has to give is telling you what he thinks of you, and telling you what he thinks of himself.",
  "The question isn't who is going to let me; it's who is going to stop me.",
  "We don't stop playing because we grow old; we grow old because we stop playing.",
  "Education costs money. But then so does ignorance.",
  "Success at the highest level comes down to one question: Can you decide that your happiness can come from someone else's success?"
  "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.",
  "Fear is only as deep as the mind allows.",
  "Just keep going. Everybody gets better if they keep at it.",
  "We must let go of the life we have planned, so as to accept the one that is waiting for us.",
  "Speak less than you know; have more than you show.",
  "Everything has beauty, but not everyone can see.",
  "What great thing would you attempt if you knew you could not fail?"
  "What lies behind you and what lies in front of you pales in comparison to what lies inside of you.",
  "I cannot think of any need in childhood as strong as the need for a father's protection.",
  "If you steadfastly refused to quit, you rapidly narrowed your options to only winning.",
  "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings.",
  "Every great dream begins with a dreamer. Always remember, you have within you the strength, the patience, and the passion to reach for the stars to change the world.",
  "I'm intimidated by the fear of being average.",
  "The most difficult thing is the decision to act, the rest is merely tenacity.",
  "Everyone has ideas. They may be too busy or lack the confidence or technical ability to carry them out. But I want to carry them out. It is a matter of getting up and doing it.",
  "Power means happiness; power means hard work and sacrifice.",
  "Be the kind of person that you want people to think you are.",
  "What we think, we become.",
  "Go out there and get rich. Get so obnoxiously rich that when that tax bill comes, your first thought will be to choke on how big a check you have to write.",
  "May I never be complete. May I never be content. May I never be perfect.",
  "The achievement of one goal should be the starting point of another.",
  "They said, we have education, but what about jobs? So I started telling them, you should be taking a pledge, and the pledge should be: 'I'm not a job seeker; I'm a job giver.' Prepare yourself to be a job giver.",
  "Eventually, the nerds and the geeks will have their day.",
  "For small creatures such as we, the vastness is bearable only through love.",
  "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me.",
  "The most successful people reach the top not because they are free of limitations, but because they act in spite of their limitations.",
  "When we seek to discover the best in others, we somehow bring out the best in ourselves.",
  "When you have a dream, you've got to grab it and never let go.",
  "What we achieve inwardly will change outer reality.",
  "Wonder rather than doubt is the root of all knowledge.",
  "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for. We are the change that we seek.",
  "Opportunities don't happen. You create them.",
  "Success is empty if you arrive at the finish line alone. The best reward is to get there surrounded by winners.",
  "You grow up the day you have your first real laugh at yourself.",
  "You can't use up creativity. The more you use, the more you have.",
  "Easter spells out beauty, the rare beauty of new life.",
  "No matter what people tell you, words and ideas can change the world.",
  "You must do the things you think you cannot do.",
  "No act of kindness, no matter how small, is ever wasted.",
  "Yesterday's home runs don't win today's games.",
  "The biggest temptation is to settle for too little.",
  "If you are not embarrassed by the first version of your product, you've launched too late.",
  "The best protection any woman can have ... is courage.",
  "When deeds speak, words are nothing.",
  "Hire character. Train skill.",
  "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.",
  "Your personal life, your professional life, and your creative life are all intertwined. I went through a few very difficult years where I felt like a failure. But it was actually really important for me to go through that. Struggle, for me, is the most inspirational thing in the world.",
  "The best way out is always through.",
  "Your present circumstances don't determine where you can go; they merely determine where you start.",
  "You can't make anything viral, but you can make something good.",
  "Remember that not getting what you want is sometimes a wonderful stroke of luck.",
  "Every truth passes through three stages before it is recognized. In the first, it is ridiculed. In the second, it is opposed. In the third, it is regarded as self-evident.",
  "I love what I do, and when you love what you do, you want to be the best at it.",
  "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.",
  "The best preparation for tomorrow is doing your best today.",
  "Everything has beauty, but not everyone can see.",
  "I do not know anyone who has gotten to the top without hard work. That is the recipe. It will not always get you to the top, but should get you pretty near.",
  "Thousands of candles can be lighted from a single candle. Happiness never decreases by being shared.",
  "I think self-awareness is probably the most important thing toward being a champion.",
  "The winners in life think constantly in terms of I can, I will, and I am. Losers, on the other hand, concentrate their waking thoughts on what they should have or would have done, or what they can't do.",
  "Be peaceful, be courteous, obey the law, respect everyone; but if someone puts his hand on you, send him to the cemetery.",
  "Running a startup is like being punched in the face repeatedly, but working for a large company is like being waterboarded.",
  "The vote is the most powerful instrument ever devised by man for breaking down injustice and destroying the terrible walls which imprison men because they are different from other men.",
  "Action may not always bring happiness; but there is no happiness without action.",
  "Never limit yourself because of others' limited imagination; never limit others because of your own limited imagination.",
  "Lord, grant that I may always desire more than I can accomplish.",
  "Talent is cheaper than table salt. What separates the talented individual from the successful one is a lot of hard work.",
  "The time is always right to do what is right.",
  "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it.",
  "Don't be afraid your life will end; be afraid that it will never begin.",
  "Life has two rules: 1. Never quit; 2. Always remember rule No. 1.",
  "Just don't give up trying to do what you really want to do. Where there is love and inspiration, I don't think you can go wrong.",
  "I shouldn't even be here, so if I'm here, I better do something good.",
  "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
  "Gifts are easy. They're given, after all. Choices can be hard. You can seduce yourself with your gifts if you're not careful, and if you do, it'll probably be to the detriment of your choices.",
  "Diligence is the mother of good luck.",
  "All you need is the plan, the road map, and the courage to press on to your destination.",
  "Instead of looking at the past, I put myself ahead 20 years and try to look at what I need to do now in order to get there then.",
  "There is no such thing as failure. Failure is just life trying to move us in another direction.",
  "Someday is not a day of the week.",
  "We must believe that we are gifted for something, and that this thing, at whatever cost, must be attained.",
  "Give me a stock clerk with a goal, and I will give you a man who will make history. Give me a man without a goal, and I will give you a stock clerk.",
  "One today is worth two tomorrows.",
  "Ah, but a man's reach should exceed his grasp. Or what's a heaven for?"
  "Please think about your legacy, because you're writing it every day.",
  "The best way to find yourself is to lose yourself in the service of others.",
  "My first job was washing dishes in the basement of a nursing home for $2.10 an hour, and I learned as much about the value of hard work there as I ever did later.",
  "Without leaps of imagination, or dreaming, we lose the excitement of possibilities. Dreaming, after all, is a form of planning.",
  "If you do what you've always done, you'll get what you've always gotten.",
  "The future belongs to those who prepare for it today.",
  "No flying machine will ever fly from New York to Paris.",
  "I think the thing about that was I was always willing to work; I was not the fastest or biggest player but I was determined to be the best football player I could be on the football field and I think I was able to accomplish that through hard work.",
  "We are all ordinary. We are all boring. We are all spectacular. We are all shy. We are all bold. We are all heroes. We are all helpless. It just depends on the day.",
  "The function of leadership is to produce more leaders, not more followers.",
  "Today a reader, tomorrow a leader.",
  "America was not built on fear. America was built on courage, on imagination, and an unbeatable determination to do the job at hand.",
  "The road to success is not easy to navigate, but with hard work, drive, and passion, it's possible to achieve the American dream.",
  "I hate that word: lucky. It cheapens a lot of hard work.",
  "Either you run the day or the day runs you.",
  "A good criterion for measuring success in life is the number of people you have made happy.",
  "The trouble in America is not that we are making too many mistakes, but that we are making too few.",
  "Somewhere, something incredible is waiting to be known.",
  "The most common way people give up their power is by thinking they don't have any.",
  "Life's too mysterious; don't take it serious.",
  "Every man's life is a fairy tale written by God's fingers.",
  "Even if you're on the right track, you'll get run over if you just sit there.",
  "A leader is one who knows the way, goes the way, and shows the way.",
  "People seldom do what they believe in. They do what is convenient, then repent.",
  "If it scares you, it might be a good thing to try.",
  "We generate fears while we sit. We over come them by action. Fear is nature's way of warning us to get busy.",
  "Everybody has a great idea for a startup, and so do their relatives, and they tell me, 'You gotta build it.' I say, 'I have to believe in it.'"
  "To climb steep hills requires a slow pace at first.",
  "Follow your bliss and the universe will open doors where there were only walls.",
  "If you focus on results, you'll never change. If you focus on change, you'll get results.",
  "In order to discover new lands, one must be willing to lose sight of the shore for a very long time.",
  "I learned pretty soon that it was essential to fail and be foolish.",
  "Look at the sparrows; they do not know what they will do in the next moment. Let us literally live from moment to moment.",
  "There on the beaches of Normandy I began to reflect on the wonders of these ordinary people whose lives were laced with the markings of greatness.",
  "Life is 10 percent what happens to us and 90 percent how we react to it.",
  "Strive not to be a success but rather to be of value.",
  "Even if you fall on your face, you're still moving forward.",
  "Your most unhappy customers are your greatest source of learning.",
  "The true test of character is not how much we know how to do, but how we behave when we don't know what to do.",
  "Happiness is not something ready made. It comes from your own actions.",
  "I have found the paradox, that if you love until it hurts, there can be no more hurt, only more love.",
  "Data beats emotions.",
  "No one has as much luck around the greens as one who practices a lot.",
  "In the real world, the smartest people are people who make mistakes and learn. In school, the smartest people don't make mistakes.",
  "Constant dripping hollows out a stone.",
  "The greatest danger for most of us is not that our aim is too high and we miss it, but that it is too low and we reach it.",
  "Rule number one: 'Don't freak out.'"
  "If you don't set goals, you can't regret not reaching them.",
  "Out of difficulties grow miracles.",
  "A truly rich man is one whose children run into his arms when his hands are empty.",
  "You have it easily in your power to increase the sum total of this world's happiness now. How? By giving a few words of sincere appreciation to someone who is lonely or discouraged. Perhaps you will forget tomorrow the kind words you say today, but the recipient may cherish them over a lifetime.",
  "Fall seven times and stand up eight.",
  "The first one gets the oyster, the second gets the shell.",
  "Too low they build, who build beneath the stars.",
  "Numbing the pain for a while will only make it worse when you finally feel it.",
  "Some of the world's greatest feats were accomplished by people not smart enough to know they were impossible.",
  "All television is educational television. The question is: What is it teaching?"
  "The only place success comes before work is in the dictionary.",
  "I wish I could tell you the secret to being forever young, but no one's figured that out yet. But if you see the glass half full, simplify your life, and give yourself to a worthy cause, you will be forever happy.",
  "The two most important days in your life are the day you are born and the day you find out why.",
  "I honestly think it is better to be a failure at something you love than to be a success at something you hate.",
  "It's never too late to be what you might have been.",
  "Smooth seas do not make skillful sailors.",
  "If you can dream it, you can achieve it.",
  "If you have no critics, you'll likely have no success.",
  "When you miss a shot, never think of what you did wrong. Take the next shot thinking of what you must do right.",
  "Believe you can and you're halfway there.",
  "Winners make a habit of manufacturing their own positive expectations in advance of the event.",
  "If you obey all the rules, you miss all the fun.",
  "I tend to think you're fearless when you recognize why you should be scared of things, but do them anyway.",
  "If you hear a voice within you say you cannot paint, then by all means paint and that voice will be silenced.",
  "If everything seems under control, you're just not going fast enough.",
  "Being able to touch so many people through my businesses, and make money while doing it, is a huge blessing.",
  "Music expresses that which cannot be put into words.",
  "There is a vitality, a life force, an energy that is translated through you; and because there is only one of you in all of time, this expression is unique.",
  "As long as you're going to be thinking anyway, think big.",
  "You can't knock on opportunity's door and not be ready.",
  "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
  "If you can't fly, then run; if you can't run, then walk; if you can't walk, then crawl; but whatever you do, you have to keep moving forward.",
  "To understand the heart and mind of a person, look not at what he has already achieved, but at what he aspires to do.",
  "Good is the enemy of great.",
  "I don't think journalists in World War II were objective about the Nazis, and I don't think they should have been.",
  "The history of the world is the history of a few people who had faith in themselves.",
  "I'm a designer, and I work very hard at that. People sometimes want to put down fashion by saying it's frivolous or superficial, but it's not that way at all. It's actually very hard work.",
  "Care about what other people think, and you will always be their prisoner.",
  "Time is what we want most, but what we use worst.",
  "It is during our darkest moments that we must focus to see the light.",
  "Let yourself be silently drawn by the stronger pull of what you really love.",
  "The greater part of our misery or unhappiness is determined not by our circumstance but by our disposition.",
  "I never dreamt of success. I worked for it.",
  "Out of clutter, find simplicity. From discord, find harmony. In the middle of difficulty lies opportunity.",
  "If you see a bandwagon, it's too late.",
  "Not everything that can be counted counts, and not everything that counts can be counted.",
  "Whether you be man or woman, you will never do anything in this world without courage. It is the greatest quality of the mind next to honor.",
  "Those who don't believe in magic will never find it.",
  "There are no traffic jams along the extra mile.",
  "Nothing will work unless you do.",
  "People talk about getting lucky breaks in their careers. I'm living proof that the 'lucky breaks' theory is simply wrong. You get to make your own luck. ... The world is run by those who show up ... not those who wait to be asked.",
  "Risk more than others think is safe. Dream more than others think is practical.",
  "It's a very sobering feeling to be up in space and realize that one's safety factor was determined by the lowest bidder on a government contract.",
  "The important thing is not being afraid to take a chance. Remember, the greatest failure is to not try. Once you find something you love to do, be the best at doing it.",
  "Timing, perseverance, and 10 years of trying will eventually make you look like an overnight success.",
  "Reality is created by the mind; we can change our reality by changing our mind.",
  "It's hard work to make a four-minute program look effortless and elegant.",
  "Empty pockets never held anyone back. Only empty heads and empty hearts can do that.",
  "Being defeated is often a temporary condition. Giving up is what makes it permanent.",
  "Every child is an artist. The problem is how to remain an artist once he grows up.",
  "As you start your journey, the first thing you should do is throw away that store-bought map and begin to draw your own.",
  "The more I want to get something done, the less I call it work.",
  "I know you've heard it a thousand times before. But it's true: Hard work pays off. If you want to be good, you have to practice, practice, practice. If you don't love something, then don't do it.",
  "Winners are the ones who really listen to the truth of their hearts.",
  "One person with a belief is equal to 99 who have only interests.",
  "Courage is the first of human qualities because it is the quality which guarantees all others.",
  "There are lots of bad reasons to start a company. But there's only one good, legitimate reason, and I think you know what it is: It's to change the world.",
  "I know the price of success: dedication, hard work, and an unremitting devotion to the things you want to see happen.",
  "Everyone thinks of changing the world, but no one thinks of changing himself.",
  "It doesn't matter if you try and try and try again, and fail. It does matter if you try and fail, and fail to try again.",
  "There is nothing impossible to him who will try.",
  "It takes 20 years to build a reputation and five minutes to ruin it. If you think about that, you'll do things differently.",
  "Falling down is not a failure. Failure comes when you stay where you have fallen.",
  "Following is one of the most underrated aspects of leadership. ... I have seen many a good [military unit] underachieve, because someone ... thought the commander was incompetent, and quietly worked to undermine his authority.",
  "A No. 2 pencil and a dream can take you anywhere.",
  "When I bet on horses, I never lose. Why? I bet on all the horses.",
  "Formal education will make you a living; self-education will make you a fortune.",
  "You must not only aim right, but draw the bow with all your might.",
  "Faith is the art of holding on to things your reason has once accepted, in spite of your changing moods.",
  "It's hard work making movies. It's like being a doctor: You work long hours, very hard hours, and it's emotional, tense work. If you don't really love it, then it ain't worth it.",
  "Don't let winning make you soft. Don't let losing make you quiet. Don't let your teammates down in any situation.",
  "Happy people are beautiful. They become like a mirror and they reflect that happiness.",
  "Everybody wants to be famous, but nobody wants to do the work. I live by that. You grind hard so you can play hard. At the end of the day, you put all the work in, and eventually it'll pay off. It could be in a year, it could be in 30 years. Eventually, your hard work will pay off.",
  "Start by doing what's necessary; then do what's possible; and suddenly you are doing the impossible.",
  "Men must live and create. Live to the point of tears.",
  "The best time to plant a tree was 20 years ago. The second best time is now.",
  "Sometimes you just have to put on lip gloss and pretend to be psyched.",
  "We live in the kind of society where, in almost all cases, hard work is rewarded.",
  "I say that the most liberating thing about beauty is realizing that you are the beholder.",
  "Entrepreneurship is neither a science nor an art. It is a practice.",
  "If something is important enough, even if the odds are against you, you should still do it.",
  "Let me tell you the secret that has led me to my goals: My strength lies solely in my tenacity.",
  "Everyone has a plan till they get punched in the mouth.",
  "You can't go around building a better world for people. Only people can build a better world for people. Otherwise it's just a cage.",
  "Yes, I am a dreamer. For a dreamer is one who can find his way by moonlight, and see the dawn before the rest of the world.",
  "Sometimes you can only find heaven by slowly backing away from hell.",
  "A hero is someone who has given his or her life to something bigger than oneself.",
  "What does not destroy me makes me stronger.",
  "Winners embrace hard work. They love the discipline of it, the tradeoff they're making to win. Losers, on the other hand, see it as punishment. And that's the difference.",
  "Don't worry about failure; you only have to be right once.",
  "Who sows virtue reaps honor.",
  "A lot of times, people look at the negative side of what they feel they can't do. I always look on the positive side of what I can do.",
  "The rung of a ladder was never meant to rest upon, but only to hold a man's foot long enough to enable him to put the other somewhat higher.",
  "Your time is limited, so don't waste it living someone else's life.",
  "Always be a first-rate version of yourself instead of a second-rate version of somebody else.",
  "If you aren't going all the way, why go at all?"
  "You are never too old to set another goal or to dream a new dream.",
  "An ounce of mother is worth a pound of clergy.",
  "Happiness is a quality of the soul ... not a function of one's material circumstances.",
  "I can say the willingness to get dirty has always defined us as an nation, and it's a hallmark of hard work and a hallmark of fun, and dirt is not the enemy.",
  "Life is what happens to you while you're busy making other plans.",
  "Act as if what you do makes a difference. It does.",
  "Think of how stupid the average person is, and realize half of them are stupider than that.",
  "I think one day you'll find that you're the hero you've been looking for.",
  "You are never too old to set another goal or to dream a new dream.",
  "Happiness is not the absence of problems; it's the ability to deal with them.",
  "The road to success and the road to failure are almost exactly the same.",
  "You know you're in love when you don't want to fall asleep because reality is finally better than your dreams.",
  "Opportunities multiply as they are seized.",
  "From a small seed a mighty trunk may grow.",
  "There's a tremendous bias against taking risks. Everyone is trying to optimize their ass-covering.",
  "If you have a positive attitude and constantly strive to give your best effort, eventually you will overcome your immediate problems and find you are ready for greater challenges.",
  "My parents had always preached the virtues of hard work. But hard work is one thing; economic struggle is another.",
  "You take your life in your own hands, and what happens? A terrible thing: no one to blame.",
  "You miss 100 percent of the shots you don't take.",
  "Don't tell people how to do things; tell them what to do and let them surprise you with their results.",
  "Every noble work is at first impossible.",
  "There are no secrets to success. It is the result of preparation, hard work, and learning from failure.",
  "What is not started will never get finished.",
  "Little minds are tamed and subdued by misfortune; but great minds rise above them.",
  "There are two ways of spreading light: to be the candle or the mirror that reflects it.",
  "You don't become enormously successful without encountering some really interesting problems.",
  "The common denominator of success is in forming the habit of doing the things that failures don't like to do.",
  "In real life, the act of creation is defying death. I think it's just that dumb and simple.",
  "Stop wearing your wishbone where your backbone ought to be.",
  "It needs to be said and heard: It's OK to be who you are.",
  "Life doesn't run away from nobody. Life runs at people."
]


def get_login_request(succeed):
  name = f'{names[randint(0, len(names)-1)]}'
  if not succeed:
    name = f'{name}{arrow.utcnow().timestamp}'
  return LoginRequest(email=f"{name}@gmail.com", password=f'{name}{name}')


def get_signup_request(succeed):
  name = f'{names[randint(0, len(names)-1)]}'
  if succeed:
    now = arrow.utcnow().timestamp
    return SignUpRequest(
      name=f'{name} {now}',
      email=f"{name}{now}@gmail.com",
      password=f'{name}{name}'
    )
  else:
    return SignUpRequest(
      name=name,
      email=f"{name}@gmail.com",
      password=name
    )

def get_tweet(succeed):
  if succeed:
    return TweetRequest(content=quotes[randint(0, len(quotes)-1)],
                        latitude=randint(-100, 100),
                        longtitude=randint(-100, 100))
  else:
    return TweetRequest(content=BAD_QUOTE)
